# enable c++ support
language: cpp

cache:
    apt:true

branches:
  only:
    - master

# use matrix to build on different setting
matrix:
    include:
    - os: linux
      compiler: gcc
      env: MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - doxygen
            - graphviz
            - g++-5

    - os: linux
      compiler: gcc
      env: MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - doxygen
            - graphviz
            - g++-6

before_install:
    # linux
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      eval "${MATRIX_EVAL}";
      fi
    # macOS
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install graphviz;
      brew install doxygen;
      fi

script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - make
  - make install

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
